{
 "title": "OHM infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodegroup_type",
    "label": "nodegroup_type",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,nodegroup_type)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{nodegroup_type=\"$nodegroup_type\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{node=\"$node\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", node=\"$node\"}[2m])))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node=\"$node\"} / node_memory_MemTotal_bytes{node=\"$node\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg without(cpu) (irate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode!=\"idle\", node=\"$node\"}[3m])))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg without(cpu) (irate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode=\"idle\",node=\"$node\"}[3m])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage by node",
   "type": "timeseries",
   "description": " {{nodegroup_type}}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=\"$node\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=\"$node\"} - node_memory_MemAvailable_bytes{node=\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes{node=\"$node\"})",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$node\", image!=\"\", namespace=\"default\"}[3m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$node\", namespace=\"default\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hetzner CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "Idle CPU"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode=\"user\"}[5m]))",
     "legendFormat": "User usage CPU"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!~\"idle|user\"}[5m])) * 100",
     "legendFormat": "System usage CPU"
    }
   ]
  },
  {
   "title": "Hetzner RAM Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "Usage RAM"
    },
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "Free RAM"
    }
   ]
  }
 ]
}