grafana:
  enabled: true
  adminPassword: "${GRAFANA_ADMINPASSWORD}"
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      nodes:
        url: 'https://raw.githubusercontent.com/Rub21/k8s-monitoring/main/configMaps/1860_rev32.template.json'
        token: ''
        pods:
          url: https://raw.githubusercontent.com/Rub21/k8s-monitoring/main/configMaps/14282_rev1.template.json
          token: ''
