apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: prometheus
  labels:
    name: cadvisor
    release: prometheus
spec:
  # clusterIP: None
  type: ClusterIP
  ports:
  - name: http-cadvisor
    port: 8080
    targetPort: http
  selector:
    name: cadvisor
