{
 "title": "OHM Ingress",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_interval", "label": "Time Interval", "query": "1s, 1m, 5m, 10m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Number of Uploads to OHM in  ${time_interval}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n  |~ \"/api/0\\\\.6/changeset/[0-9]+/upload\" [${time_interval}]\n)",
     "legendFormat": "Uploads"
    }
   ]
  },
  {
   "title": "Number of Downloads  to OHM in  ${time_interval}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"}\n  |~ \"/api/0\\\\.6/(map|node/[0-9]+/ways|way/[0-9]+/full|relation/[0-9]+/full|node/[0-9]+/relations|way/[0-9]+/relations|relation/[0-9]+/relations|node/[0-9]+/history|way/[0-9]+/history|relation/[0-9]+/history|changeset/[0-9]+|nodes|ways|relations)\"\n  [${time_interval}]\n)",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "Number of requests in OHM/api/0.6  in  $time_interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n  |~ \"/api/0\\\\.6\" [${time_interval}]\n)",
     "legendFormat": "openhistoricalmap.org/api/0.6"
    }
   ]
  },
  {
   "title": "Number of requests in ohm/*  in $time_interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n  |~ \"api\\\\.openhistoricalmap\\\\.org|www\\\\.openhistoricalmap\\\\.org|openhistoricalmap\\\\.org\" \n  [${time_interval}]\n)",
     "legendFormat": "openhistoricalmap.org"
    }
   ]
  },
  {
   "title": "Number of requests in vtiles  in $time_interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n sum by (zoom) (\n  count_over_time(\n    {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n    | regexp \".*\\\\/maps\\\\/(osm|ne)\\\\/(?P<zoom>0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20)\\\\/[0-9]+\\\\/[0-9]+\\\\.pbf\"\n    [${time_interval}]\n  )\n) unless sum by (zoom) (\n  count_over_time({job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} [${time_interval}])\n)\n)"
    }
   ]
  },
  {
   "title": "Number of requests to Vtiles  in the last $time_interval",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (zoom) (\n  count_over_time(\n    {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n    | regexp \".*\\\\/maps\\\\/(osm|ne)\\\\/(?P<zoom>0|1|2|3|4|5|6|7|8|9)\\\\/[0-9]+\\\\/[0-9]+\\\\.pbf\"\n    [${time_interval}]\n  )\n) unless sum by (zoom) (\n  count_over_time({job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} [${time_interval}])\n)",
     "legendFormat": "zoom={{zoom}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (zoom) (\n  count_over_time(\n    {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n    | regexp \".*\\\\/maps\\\\/(osm|ne)\\\\/(?P<zoom>10|11|12|13|14|15|16|17|18|19|20)\\\\/[0-9]+\\\\/[0-9]+\\\\.pbf\"\n    [${time_interval}]\n  )\n) unless sum by (zoom) (\n  count_over_time({job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} [${time_interval}])\n)",
     "legendFormat": "zoom={{zoom}}"
    }
   ]
  },
  {
   "title": "Number of requests in openhistoricalmap.org and openhistoricalmap.org/api/0.6",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n  |~ \"api\\\\.openhistoricalmap\\\\.org|www\\\\.openhistoricalmap\\\\.org|openhistoricalmap\\\\.org\" \n  [${time_interval}]\n)",
     "legendFormat": "openhistoricalmap.org"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n  |~ \"/api/0\\\\.6\" [${time_interval}]\n)",
     "legendFormat": "openhistoricalmap.org/api/0.6"
    }
   ]
  },
  {
   "title": "Number of Downloads  to OHM ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"}\n  |~ \"/api/0\\\\.6/(map|node/[0-9]+/ways|way/[0-9]+/full|relation/[0-9]+/full|node/[0-9]+/relations|way/[0-9]+/relations|relation/[0-9]+/relations|node/[0-9]+/history|way/[0-9]+/history|relation/[0-9]+/history|changeset/[0-9]+|nodes|ways|relations)\"\n  [${time_interval}]\n)",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "Number of Uploads to OHM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n  |~ \"/api/0\\\\.6/changeset/[0-9]+/upload\" [${time_interval}]\n)",
     "legendFormat": "Uploads"
    }
   ]
  },
  {
   "title": "Requests per minute by Zoom Level (OHM Tiles)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (zoom) (\n  count_over_time(\n    {job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} \n    | regexp \".*\\\\/maps\\\\/osm\\\\/(?P<zoom>[0-9]+)\\\\/[0-9]+\\\\/[0-9]+\\\\.pbf\"\n    [${time_interval}]\n  )\n) unless sum by (zoom) (count_over_time({job=\"ingress-nginx/ingress-nginx\", stream=\"stdout\"} [${time_interval}]))",
     "legendFormat": "zoom={{zoom}}"
    }
   ]
  }
 ]
}